version: '3.7'

services:
  backend:
    container_name: fast-api-backend
    build:
      context: /fastapi_backend
    env_file:
      - fastapi_backend/.env-prod
    command: ["/backend/docker/backend.sh"]
    volumes:
      - /home/site/photo:/photos
    ports:
      - 6748:8000
