"""empty message

Revision ID: 4e377c16dea7
Revises: 8d6e36a3f37a
Create Date: 2023-05-25 19:45:56.578634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e377c16dea7'
down_revision = '8d6e36a3f37a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
