"""empty message

Revision ID: 5b3b0d588cdb
Revises: 463c1b7e16ad
Create Date: 2023-06-20 16:56:51.292778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3b0d588cdb'
down_revision = '463c1b7e16ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
